### ISSUE TITLE
Missing PKCE Parameters

### ISSUE THREAD

**Issue by Euan-Gutsell** [Snapchat/passport-snapchat#1]
Followed the documentation exactly, and tried with [the example](https://github.com/Snapchat/express-4.x-passport-snapchat-example), however the following is returned:

`{"error":"invalid_request","error_description":"Missing PKCE parameters."}`

The strategy is as follows:

`passport.use(new SnapchatStrategy({
            clientID: "    ",
            clientSecret: "    ",
            callbackURL: "http://localhost:8000/auth/snapchat/callback",
            profileFields: ['id', 'displayName', 'bitmoji'],
            scope: ['user.display_name', 'user.bitmoji.avatar']
        },
        function (accessToken, refreshToken, profile, cb) {
            User.findOrCreate({
                snapchatId: profile.id
            }, function (err, user) {
                return cb(err, user);
            });
        }
    ));`

Any ideas?
Thanks

**Comment by mr-mad-e** [comment]
*CLIENT ID FOR CONFIDENTIAL OAUTH2 FLOW* is **SNAPCHAT_ID**, *CLIENT SECRET FOR CONFIDENTIAL OAUTH2 FLOW* is **SNAPCHAT_SECRET**
