### ISSUE TITLE
/v1/me returns unauthorized

### ISSUE THREAD

**Issue by gopinav** [Snapchat/passport-snapchat#2]
Hi, I've been using this package since March. The users created back then are successfully authenticated in my app. However, I newly created a snapchat account last week and ever since, I always get back unauthorized error from  snapchat /v1/me API.

The old accounts continue to pass authentication but any new snapchat accounts fail at 
passport.authenticate('snapchat')

Please let me know if something has to be corrected. Thanks

**Comment by iansebas** [comment]
I have the same problem. Any updates?

**Comment by gopinav** [comment]
It turns out that I was using dev env keys so only the sandbox users were working. Make sure you are using prod env keys
